import { esc } from './operations.js';
export function lifecycleState(client){return client.lifecycle_state || (client.status==='Suspended'?'Suspended':'Active');}
export function canContactShop(client){return lifecycleState(client)!=='Archived' && !['destroyed','decommissioned'].includes(client.infrastructure_state);}
export function visibleClients(clients,view='current',filter=''){
 return clients.filter(c=>(view==='all' || (lifecycleState(c)==='Archived')===(view==='historical')) && `${c.name} ${c.id} ${c.shop_url || ''}`.toLowerCase().includes(filter.toLowerCase()));
}
export function publicEnvironment(client,anon,site){
 if(!/^https:\/\/[a-z]{20}\.supabase\.co$/.test(client.supabase_url || ''))throw Error('Exact Shop URL required.');
 let claims;try{claims=JSON.parse(atob(anon.split('.')[1].replaceAll('-','+').replaceAll('_','/')));}catch{throw Error('Use the public Shop anon JWT, never a service/secret key.');}
 if(claims.role!=='anon' || /[\r\n]/.test(anon) || !site || /\s/.test(site))throw Error('Only public Shop anon and site keys are allowed.');
 return `VITE_SUPABASE_URL=${client.supabase_url}\nVITE_SUPABASE_ANON=${anon}\nVITE_TURNSTILE_SITE_KEY=${site}`;
}
export function lifecyclePanel(client,detail,master){
 const jobs=detail.overhaul?.config_jobs || [], stages=detail.overhaul?.stages || [], job=detail.provisioning?.job;
 const actionForm=(type,request,buttons)=>`<form data-p-form="${type}" class="form-grid"><input type="hidden" name="request_id" value="${esc(request)}"><label class="field"><span>Audited reason</span><input name="reason" required minlength="10" maxlength="500"></label><div>${buttons}</div></form>`;
 const button=(action,label)=>`<button class="secondary-button" name="action" value="${action}">${label}</button>`;
 return `<section class="card"><h2>Client lifecycle</h2><p>${esc(lifecycleState(client))} · Infrastructure: ${esc(client.infrastructure_state || 'unknown')}</p><p>Archive retains billing, usage and audit history and stops Platform coordination. It does not destroy the Shop or revoke a reachable Shop’s access; Suspend first if access must stop.</p>
 ${master?`<form data-p-form="client-lifecycle" class="form-grid"><label class="field"><span>Audited reason</span><input name="reason" required minlength="10" maxlength="500"></label><label class="field"><span>Exact project ref (required when recording destroyed/retired infrastructure)</span><input name="project_ref" pattern="[a-z]{20}" maxlength="20"></label><label><input type="checkbox" name="confirmed" required> I understand that Archive is local; infrastructure retirement must already have been performed separately.</label><div>${lifecycleState(client)!=='Archived'?button('archive','Archive / Retire client'):''}${button('mark-destroyed','Record infrastructure already destroyed')}${button('mark-decommissioned','Record completed manual decommission')}</div></form>`:'<p>Lifecycle recovery requires the master administrator.</p>'}
 <p class="muted">Automatic remote infrastructure deletion is deferred. Perform deletion separately only after backups, retention review and verified project identity. No historical deletion action is provided.</p></section>
 <section class="card"><h2>Operation recovery</h2>${detail.overhaulError?`<p role="alert">${esc(detail.overhaulError)}</p>`:''}
 ${jobs.map(j=>`<article><h3>Configuration · ${esc(j.state)}</h3><p>Request ${esc(j.request_id)} · Created ${esc(j.created_at)} · Updated ${esc(j.updated_at)}</p><p>Intended change: ${esc(JSON.stringify(j.changes))}</p><p>Last local state: ${esc(client.status)} · Last remote observation: ${esc(JSON.stringify(j.result || 'Unknown'))}</p>${master?actionForm('config-recovery',j.request_id,button('read','Read Shop state')+button('reconcile','Reconcile from read-back')+button('retry','Retry SAME request')+button('close','Close with unknown remote outcome')):''}</article>`).join('') || '<p>No unresolved configuration operations.</p>'}
 ${job && job.state!=='complete'?`<article><h3>Provisioning · ${esc(job.state)}</h3><p>Request ${esc(job.request_id)} · ${esc(job.action)} · ${esc(job.updated_at)}</p><p>${esc(job.error || 'Running / outcome not yet recorded')}</p>${master?actionForm('provision-recovery',job.request_id,button('resume','Release for safe same-request retry')+button('close','Close with audited reason')):''}</article>`:''}
 <p class="muted">Server records are authoritative. Configuration recovery waits 60 seconds; an interrupted provisioner waits ten minutes. Read-back mismatch remains unresolved. Retired infrastructure can be archived locally.</p></section>
 ${stages.length?`<section class="card"><h2>Managed provisioning stages</h2><ul>${['project-access','migrations','server-secrets','turnstile','functions','bridge-owner','preflight'].map(name=>{const s=stages.find(s=>s.name===name);return `<li>${esc(name)} · <strong>${esc(s?.state==='failed'?'failed · retryable':s?.state==='manual'?'requires manual action':s?.state || 'pending')}</strong> · ${esc(s?.updated_at || '')}</li>`;}).join('')}</ul><details><summary>Migration / function checkpoints</summary><ul>${stages.filter(s=>s.name.includes(':')).map(s=>`<li>${esc(s.name)} · ${esc(s.state)} · ${esc(s.updated_at)}</li>`).join('')}</ul></details><p>Passed stages are retained. Retry the recorded request; a changed release requires reconciliation.</p></section>`:''}
 <details class="card"><summary>Lifecycle / provisioning audit</summary>${(detail.overhaul?.audit || []).map(a=>`<p>${esc(a.created_at)} · Actor ${esc(a.actor_id)} · ${esc(a.action)} · ${esc(JSON.stringify(a.detail))}</p>`).join('') || '<p>No recorded audit events.</p>'}</details>`;
}
